create table invoice (
                         id bigint generated by default as identity,
                         buyer_address_city varchar(255),
                         buyer_address_country varchar(255),
                         buyer_address_street varchar(255),
                         buyer_address_zip_code varchar(255),
                         buyer_email varchar(255),
                         buyer_name varchar(255),
                         buyer_phone_number varchar(255),
                         create_time timestamp(6) with time zone,
                         currency varchar(3),
                         due_time timestamp(6) with time zone,
                         invoice_date timestamp(6) with time zone,
                         invoice_header varchar(255),
                         invoice_status varchar(255),
                         modify_time timestamp(6) with time zone,
                         paid boolean not null,
                         payment_link varchar(255),
                         seller_address_city varchar(255),
                         seller_address_country varchar(255),
                         seller_address_street varchar(255),
                         seller_address_zip_code varchar(255),
                         seller_email varchar(255),
                         seller_name varchar(255),
                         seller_phone_number varchar(255),
                         total_amount numeric(38,2),
                         total_tax_amount numeric(38,2),
                         uuid uuid,
                         version integer,
                         owner_id bigint,
                         primary key (id)
);

create table lineitem (
                          id bigint generated by default as identity,
                          amount_per_item numeric(38,2),
                          create_time timestamp(6) with time zone,
                          description varchar(255),
                          modify_time timestamp(6) with time zone,
                          quantity integer,
                          tax numeric(38,2),
                          total_amount numeric(38,2),
                          total_tax_amount numeric(38,2),
                          version integer,
                          invoice bigint,
                          primary key (id)
);

CREATE TABLE owner (
                        id SERIAL PRIMARY KEY,
                        username VARCHAR(255) NOT NULL,
                        password VARCHAR(255) NOT NULL
);
--password 'admin123'
INSERT INTO owner (username, password)
VALUES ('admin', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2');